import { createCipheriv, createDecipheriv, randomBytes, scryptSync } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path';

import { loadConfig } from '@elitjs/config';

import { resolveArchiveHandle } from './remote';
import {
    DEFAULT_IGNORE,
    DEFAULT_WAPK_ENTRY_CANDIDATES,
    WAPK_LOCKED_VERSION,
    WAPK_UNLOCKED_VERSION,
    WAPK_VERSION,
    RUNTIME_SYNC_IGNORE,
    type DecodedWapk,
    type ResolvedWapkCredentials,
    type WapkArchiveHandle,
    type WapkCredentialsOptions,
    type WapkFileEntry,
    type WapkHeader,
    type WapkPatchResult,
    type WapkProjectConfig,
    ensureBufferRange,
    findNearestPackageDirectory,
    inferRuntimeAndEntryFromScript,
    isRecord,
    normalizeArchivePath,
    normalizeDesktopConfig,
    normalizeNonEmptyString,
    normalizePackageEntry,
    normalizePort,
    normalizeRuntime,
    normalizeStringMap,
    normalizeWapkConfig,
    readJsonFile,
    resolveArchiveCredentials,
    resolveAutoGeneratedWapkAppId,
    resolveAutoGeneratedWapkPublisherId,
    resolveBuildEntryCandidate,
    resolveExistingWapkEntry,
    resolvePackLockCredentials,
    sanitizePackageName,
} from './shared';

interface WapkLockMetadata {
    cipher: 'aes-256-gcm';
    kdf: 'scrypt';
    salt: string;
    iv: string;
    tag: string;
    user?: string;
}

type ParsedWapkEnvelope =
    | { version: 1; payload: Buffer }
    | { version: 2; payload: Buffer; lock: WapkLockMetadata };

const WAPK_MAGIC = Buffer.from('WAPK');
const WAPK_CIPHER = 'aes-256-gcm';
const WAPK_KDF = 'scrypt';
const WAPK_KEY_LENGTH = 32;
const WAPK_SALT_LENGTH = 16;
const WAPK_IV_LENGTH = 12;
const WAPK_AUTH_TAG_LENGTH = 16;
const WAPK_SCRYPT_OPTIONS = { N: 16384, r: 8, p: 1 } as const;

function buildWapkAuthData(legacyUser?: string): Buffer {
    return Buffer.from(legacyUser ? `WAPK:${legacyUser}` : 'WAPK', 'utf8');
}

function encryptWapkPayload(payload: Buffer, lock: ResolvedWapkCredentials): { metadata: WapkLockMetadata; payload: Buffer } {
    const salt = randomBytes(WAPK_SALT_LENGTH);
    const iv = randomBytes(WAPK_IV_LENGTH);
    const key = scryptSync(lock.password, salt, WAPK_KEY_LENGTH, WAPK_SCRYPT_OPTIONS);
    const cipher = createCipheriv(WAPK_CIPHER, key, iv);
    cipher.setAAD(buildWapkAuthData());

    const encryptedPayload = Buffer.concat([cipher.update(payload), cipher.final()]);
    const tag = cipher.getAuthTag();

    return {
        metadata: {
            cipher: WAPK_CIPHER,
            kdf: WAPK_KDF,
            salt: salt.toString('base64'),
            iv: iv.toString('base64'),
            tag: tag.toString('base64'),
        },
        payload: encryptedPayload,
    };
}

function decodeLockBuffer(value: string, expectedLength: number, field: string): Buffer {
    const buffer = Buffer.from(value, 'base64');
    if (buffer.length !== expectedLength) {
        throw new Error(`Invalid WAPK file: bad ${field}.`);
    }
    return buffer;
}

function decryptWapkPayload(payload: Buffer, lock: WapkLockMetadata, credentials: ResolvedWapkCredentials): Buffer {
    const salt = decodeLockBuffer(lock.salt, WAPK_SALT_LENGTH, 'lock salt');
    const iv = decodeLockBuffer(lock.iv, WAPK_IV_LENGTH, 'lock iv');
    const tag = decodeLockBuffer(lock.tag, WAPK_AUTH_TAG_LENGTH, 'lock auth tag');
    const key = scryptSync(credentials.password, salt, WAPK_KEY_LENGTH, WAPK_SCRYPT_OPTIONS);
    const decipher = createDecipheriv(WAPK_CIPHER, key, iv);
    decipher.setAAD(buildWapkAuthData(lock.user));
    decipher.setAuthTag(tag);

    try {
        return Buffer.concat([decipher.update(payload), decipher.final()]);
    } catch {
        throw new Error('Invalid WAPK credentials.');
    }
}

function parseWapkLockMetadata(rawMetadata: unknown): WapkLockMetadata {
    if (!isRecord(rawMetadata)) {
        throw new Error('Invalid WAPK file: lock metadata must be an object.');
    }

    if (rawMetadata.cipher !== WAPK_CIPHER) {
        throw new Error(`Unsupported WAPK cipher: ${String(rawMetadata.cipher)}`);
    }

    if (rawMetadata.kdf !== WAPK_KDF) {
        throw new Error(`Unsupported WAPK KDF: ${String(rawMetadata.kdf)}`);
    }

    if (typeof rawMetadata.salt !== 'string' || typeof rawMetadata.iv !== 'string' || typeof rawMetadata.tag !== 'string') {
        throw new Error('Invalid WAPK file: lock metadata is incomplete.');
    }

    return {
        cipher: WAPK_CIPHER,
        kdf: WAPK_KDF,
        salt: rawMetadata.salt,
        iv: rawMetadata.iv,
        tag: rawMetadata.tag,
        user: normalizeNonEmptyString(rawMetadata.user),
    };
}

export function parseWapkEnvelope(buffer: Buffer): ParsedWapkEnvelope {
    let offset = 0;

    ensureBufferRange(buffer, offset, 4, 'magic');
    if (!buffer.slice(offset, offset + 4).equals(WAPK_MAGIC)) {
        throw new Error('Invalid WAPK file: bad magic bytes.');
    }
    offset += 4;

    ensureBufferRange(buffer, offset, 2, 'version');
    const version = buffer.readUInt16LE(offset);
    offset += 2;
    if (version > WAPK_VERSION) {
        throw new Error(`Unsupported WAPK version: ${version}`);
    }

    if (version === WAPK_UNLOCKED_VERSION) {
        return {
            version: WAPK_UNLOCKED_VERSION,
            payload: buffer.subarray(offset),
        };
    }

    ensureBufferRange(buffer, offset, 4, 'lock metadata length');
    const metadataLength = buffer.readUInt32LE(offset);
    offset += 4;

    ensureBufferRange(buffer, offset, metadataLength, 'lock metadata');
    const metadata = JSON.parse(buffer.slice(offset, offset + metadataLength).toString('utf8'));
    offset += metadataLength;

    ensureBufferRange(buffer, offset, 4, 'encrypted payload length');
    const payloadLength = buffer.readUInt32LE(offset);
    offset += 4;

    ensureBufferRange(buffer, offset, payloadLength, 'encrypted payload');
    const payload = buffer.slice(offset, offset + payloadLength);

    return {
        version: WAPK_LOCKED_VERSION,
        payload,
        lock: parseWapkLockMetadata(metadata),
    };
}

async function readWapkProjectConfig(directory: string): Promise<WapkProjectConfig> {
    const packageJsonPath = join(directory, 'package.json');
    const elitConfig = await loadConfig(directory);
    const elitWapkConfig = normalizeWapkConfig(elitConfig?.wapk);
    const packageJson = readJsonFile(packageJsonPath);
    const packageJsonWapk = isRecord(packageJson?.wapk) ? packageJson.wapk : undefined;

    const packageScripts = normalizeStringMap(packageJson?.scripts) ?? {};
    const selectedScripts = elitWapkConfig.scripts ?? packageScripts;
    const inferred = inferRuntimeAndEntryFromScript(selectedScripts.start ?? packageScripts.start);
    const name = typeof elitWapkConfig.name === 'string'
        ? elitWapkConfig.name
        : typeof packageJson?.name === 'string'
            ? packageJson.name
            : basename(directory);
    const version = typeof elitWapkConfig.version === 'string'
        ? elitWapkConfig.version
        : typeof packageJson?.version === 'string'
            ? packageJson.version
            : '1.0.0';
    const runtime = elitWapkConfig.runtime
        ?? inferred.runtime
        ?? 'node';
    const configuredEntry = normalizeNonEmptyString(elitWapkConfig.entry);
    const entry = configuredEntry
        ? normalizeArchivePath(directory, configuredEntry)
        : resolveExistingWapkEntry(directory, [
            typeof packageJson?.main === 'string' ? packageJson.main : undefined,
            typeof packageJson?.module === 'string' ? packageJson.module : undefined,
            inferred.entry,
            resolveBuildEntryCandidate(elitConfig),
            ...DEFAULT_WAPK_ENTRY_CANDIDATES,
        ]);

    if (!entry) {
        throw new Error(
            `WAPK entry could not be inferred. Set wapk.entry, package.json main, build.entry, or add one of: ${DEFAULT_WAPK_ENTRY_CANDIDATES.join(', ')}`,
        );
    }

    const entryPath = resolve(directory, entry);

    if (!existsSync(entryPath) || !statSync(entryPath).isFile()) {
        throw new Error(`WAPK entry not found: ${entryPath}`);
    }

    const appId = elitWapkConfig.appId
        ?? normalizeNonEmptyString(packageJson?.appId)
        ?? normalizeNonEmptyString(packageJsonWapk?.appId)
        ?? resolveAutoGeneratedWapkAppId(typeof packageJson?.name === 'string' ? packageJson.name : undefined, name);
    const publisherId = elitWapkConfig.publisherId
        ?? normalizeNonEmptyString(packageJson?.publisherId)
        ?? normalizeNonEmptyString(packageJsonWapk?.publisherId)
        ?? resolveAutoGeneratedWapkPublisherId(packageJson, name);

    return {
        name,
        version,
        runtime,
        entry,
        scripts: selectedScripts,
        appId,
        publisherId,
        port: elitWapkConfig.port,
        env: elitWapkConfig.env,
        desktop: elitWapkConfig.desktop,
        lock: elitWapkConfig.lock,
    };
}

function readIgnorePatterns(directory: string): string[] {
    return readLineIgnorePatterns(join(directory, '.wapkignore'));
}

function parsePatternLines(content: string): string[] {
    return content
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line.length > 0 && (!line.startsWith('#') || line.startsWith('\\#')));
}

function readLineIgnorePatterns(filePath: string): string[] {
    if (!existsSync(filePath)) {
        return [];
    }

    return parsePatternLines(readFileSync(filePath, 'utf8'));
}

function collectStringLeaves(value: unknown, target: Set<string>): void {
    if (typeof value === 'string') {
        const normalized = normalizePackageEntry(value);
        if (normalized) {
            target.add(normalized);
        }
        return;
    }

    if (Array.isArray(value)) {
        for (const entry of value) {
            collectStringLeaves(entry, target);
        }
        return;
    }

    if (!isRecord(value)) {
        return;
    }

    for (const entry of Object.values(value)) {
        collectStringLeaves(entry, target);
    }
}

function collectPackageTopLevelEntries(directory: string): string[] {
    return readdirSync(directory, { withFileTypes: true })
        .filter((entry) => entry.name !== 'node_modules' && entry.name !== '.git' && !entry.name.startsWith('.'))
        .map((entry) => entry.name);
}

function collectLinkedPackageCandidates(directory: string): string[] {
    const packageJson = readJsonFile(join(directory, 'package.json'));
    if (!packageJson) {
        return [];
    }

    const candidates = new Set<string>(['package.json']);
    const packageFiles = Array.isArray(packageJson.files)
        ? packageJson.files.filter((value): value is string => typeof value === 'string')
        : [];

    if (packageFiles.length > 0) {
        for (const file of packageFiles) {
            const normalized = normalizePackageEntry(file);
            if (normalized) {
                candidates.add(normalized);
            }
        }
    } else {
        const runtimeEntries = new Set<string>();
        for (const value of [packageJson.main, packageJson.module, packageJson.browser, packageJson.types, packageJson.typings]) {
            collectStringLeaves(value, runtimeEntries);
        }

        if (typeof packageJson.bin === 'string') {
            collectStringLeaves(packageJson.bin, runtimeEntries);
        } else if (isRecord(packageJson.bin)) {
            collectStringLeaves(Object.values(packageJson.bin), runtimeEntries);
        }

        collectStringLeaves(packageJson.exports, runtimeEntries);

        for (const entry of runtimeEntries) {
            const rootEntry = entry.includes('/') ? entry.split('/')[0] ?? entry : entry;
            if (rootEntry) {
                candidates.add(rootEntry);
            }
        }

        if (candidates.size === 1) {
            for (const fallback of ['dist', 'src']) {
                if (existsSync(join(directory, fallback))) {
                    candidates.add(fallback);
                }
            }
        }

        if (candidates.size === 1) {
            for (const fallbackEntry of collectPackageTopLevelEntries(directory)) {
                candidates.add(fallbackEntry);
            }
        }
    }

    for (const metadataFile of ['README.md', 'README', 'LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'CHANGELOG.md']) {
        if (existsSync(join(directory, metadataFile))) {
            candidates.add(metadataFile);
        }
    }

    return [...candidates];
}

function prefixCollectedFiles(files: readonly WapkFileEntry[], prefix: string): WapkFileEntry[] {
    return files.map((file) => ({
        ...file,
        path: `${prefix}/${file.path}`,
    }));
}

function collectInstalledPackageNames(packageJson: Record<string, unknown>): string[] {
    const packageNames = new Set<string>();

    for (const dependencyGroup of [
        packageJson.dependencies,
        packageJson.optionalDependencies,
        packageJson.peerDependencies,
    ]) {
        if (!isRecord(dependencyGroup)) {
            continue;
        }

        for (const packageName of Object.keys(dependencyGroup)) {
            const normalizedPackageName = normalizeNonEmptyString(packageName);
            if (normalizedPackageName) {
                packageNames.add(normalizedPackageName);
            }
        }
    }

    return [...packageNames];
}

function resolveInstalledPackageDirectory(startDirectory: string, packageName: string): string | undefined {
    let currentDirectory = resolve(startDirectory);

    while (true) {
        const candidate = join(currentDirectory, 'node_modules', ...packageName.split('/'));
        if (existsSync(candidate)) {
            return candidate;
        }

        const parentDirectory = dirname(currentDirectory);
        if (parentDirectory === currentDirectory) {
            return undefined;
        }

        currentDirectory = parentDirectory;
    }
}

function collectLinkedPackageFiles(
    linkPath: string,
    archivePrefix: string,
    seenPackages: Set<string> = new Set(),
): WapkFileEntry[] {
    const packageRoot = realpathSync(linkPath);
    if (seenPackages.has(packageRoot)) {
        return [];
    }

    seenPackages.add(packageRoot);
    const candidates = collectLinkedPackageCandidates(packageRoot);
    if (candidates.length === 0) {
        return [];
    }

    const ignorePatterns = ['node_modules', ...readLineIgnorePatterns(join(packageRoot, '.npmignore'))];
    const collected = new Map<string, WapkFileEntry>();

    for (const candidate of candidates) {
        let relativeCandidate: string;
        try {
            relativeCandidate = normalizeArchivePath(packageRoot, candidate);
        } catch {
            continue;
        }

        const fullCandidatePath = resolve(packageRoot, relativeCandidate);
        if (!existsSync(fullCandidatePath)) {
            continue;
        }

        const stats = statSync(fullCandidatePath);
        const entries = stats.isDirectory()
            ? prefixCollectedFiles(collectFiles(fullCandidatePath, packageRoot, ignorePatterns), archivePrefix)
            : stats.isFile()
                ? [{
                    path: `${archivePrefix}/${relativeCandidate}`,
                    content: readFileSync(fullCandidatePath),
                    mode: stats.mode,
                }]
                : [];

        for (const entry of entries) {
            collected.set(entry.path, entry);
        }
    }

    const packageJson = readJsonFile(join(packageRoot, 'package.json'));
    if (packageJson) {
        for (const dependencyName of collectInstalledPackageNames(packageJson)) {
            const dependencyDirectory = resolveInstalledPackageDirectory(packageRoot, dependencyName);
            if (!dependencyDirectory) {
                continue;
            }

            const dependencyEntries = collectLinkedPackageFiles(
                dependencyDirectory,
                resolveLinkedDependencyArchivePrefix(archivePrefix, dependencyName),
                seenPackages,
            );
            for (const entry of dependencyEntries) {
                collected.set(entry.path, entry);
            }
        }
    }

    return [...collected.values()];
}

function resolveLinkedDependencyArchivePrefix(archivePrefix: string, dependencyName: string): string {
    const normalizedPrefix = archivePrefix.split('\\').join('/');
    const marker = '/node_modules/';
    const markerIndex = normalizedPrefix.lastIndexOf(marker);

    if (markerIndex === -1) {
        return `node_modules/${dependencyName}`;
    }

    return `${normalizedPrefix.slice(0, markerIndex + marker.length)}${dependencyName}`;
}

function escapeRegex(text: string): string {
    return text.replace(/[|\\{}()[\]^$+?.]/g, '\\$&');
}

function globPatternToRegex(pattern: string, options: { directoryOnly?: boolean; matchSegmentsOnly?: boolean } = {}): RegExp {
    let regex = '';

    for (let index = 0; index < pattern.length; index++) {
        const char = pattern[index];

        if (char === '*') {
            const nextChar = pattern[index + 1];
            const nextNextChar = pattern[index + 2];

            if (nextChar === '*') {
                if (nextNextChar === '/') {
                    regex += '(?:.*?/)?';
                    index += 2;
                    continue;
                }

                regex += '.*';
                index += 1;
                continue;
            }

            regex += '[^/]*';
            continue;
        }

        if (char === '?') {
            regex += '[^/]';
            continue;
        }

        regex += escapeRegex(char);
    }

    const suffix = options.directoryOnly ? '(?:$|/.*)' : '$';
    const prefix = options.matchSegmentsOnly ? '^(?:.*?/)?' : '^';

    return new RegExp(`${prefix}${regex}${suffix}`);
}

function normalizeIgnorePattern(pattern: string): {
    directoryOnly: boolean;
    matchSegmentsOnly: boolean;
    negate: boolean;
    pattern: string;
} | undefined {
    let normalizedPattern = pattern.trim();
    if (!normalizedPattern) {
        return undefined;
    }

    let negate = false;
    if (normalizedPattern.startsWith('\\!') || normalizedPattern.startsWith('\\#')) {
        normalizedPattern = normalizedPattern.slice(1);
    } else if (normalizedPattern.startsWith('!')) {
        negate = true;
        normalizedPattern = normalizedPattern.slice(1).trim();
    }

    if (!normalizedPattern) {
        return undefined;
    }

    const directoryOnly = normalizedPattern.endsWith('/');
    if (directoryOnly) {
        normalizedPattern = normalizedPattern.replace(/\/+$/, '');
    }

    normalizedPattern = normalizedPattern
        .replace(/^\.\//, '')
        .replace(/^\//, '')
        .replace(/\\/g, '/');

    if (!normalizedPattern) {
        return undefined;
    }

    return {
        directoryOnly,
        matchSegmentsOnly: !normalizedPattern.includes('/'),
        negate,
        pattern: normalizedPattern,
    };
}

function matchesIgnorePattern(relativePath: string, pattern: string, isDirectory: boolean): boolean {
    const normalizedRule = normalizeIgnorePattern(pattern);
    if (!normalizedRule) {
        return false;
    }

    if (normalizedRule.directoryOnly && !isDirectory) {
        return false;
    }

    const hasGlob = /[*?]/.test(normalizedRule.pattern);
    if (!hasGlob) {
        if (normalizedRule.matchSegmentsOnly) {
            return relativePath === normalizedRule.pattern || relativePath.split('/').includes(normalizedRule.pattern);
        }

        return relativePath === normalizedRule.pattern;
    }

    if (normalizedRule.matchSegmentsOnly) {
        const segmentRegex = globPatternToRegex(normalizedRule.pattern);
        return relativePath.split('/').some((segment) => segmentRegex.test(segment));
    }

    return globPatternToRegex(normalizedRule.pattern, { directoryOnly: normalizedRule.directoryOnly }).test(relativePath);
}

function shouldIgnore(relativePath: string, ignorePatterns: readonly string[], isDirectory: boolean): boolean {
    let ignored = false;

    for (const pattern of ignorePatterns) {
        const normalizedRule = normalizeIgnorePattern(pattern);
        if (!normalizedRule) {
            continue;
        }

        if (!matchesIgnorePattern(relativePath, pattern, isDirectory)) {
            continue;
        }

        ignored = !normalizedRule.negate;
    }

    return ignored;
}

function matchesPatchPattern(relativePath: string, pattern: string): boolean {
    const normalizedRule = normalizeIgnorePattern(pattern);
    if (!normalizedRule) {
        return false;
    }

    const normalizedPath = relativePath.replace(/\\/g, '/');
    const subtreeSelector = normalizedRule.pattern.endsWith('/*')
        && !normalizedRule.pattern.slice(0, -2).includes('*')
        && !normalizedRule.pattern.slice(0, -2).includes('?');

    if (subtreeSelector) {
        const directoryPath = normalizedRule.pattern.slice(0, -2);
        return directoryPath.length > 0 && normalizedPath.startsWith(`${directoryPath}/`);
    }

    const hasGlob = /[*?]/.test(normalizedRule.pattern);

    if (!hasGlob) {
        if (normalizedRule.directoryOnly) {
            return normalizedPath === normalizedRule.pattern
                || normalizedPath.startsWith(`${normalizedRule.pattern}/`);
        }

        return normalizedPath === normalizedRule.pattern;
    }

    return globPatternToRegex(normalizedRule.pattern, {
        directoryOnly: normalizedRule.directoryOnly,
        matchSegmentsOnly: false,
    }).test(normalizedPath);
}

function shouldPatchArchivePath(relativePath: string, patchPatterns: readonly string[]): boolean {
    let selected = false;

    for (const pattern of patchPatterns) {
        const normalizedRule = normalizeIgnorePattern(pattern);
        if (!normalizedRule) {
            continue;
        }

        if (!matchesPatchPattern(relativePath, pattern)) {
            continue;
        }

        selected = !normalizedRule.negate;
    }

    return selected;
}

function resolvePatchManifestPatterns(files: readonly WapkFileEntry[]): string[] {
    const patchManifest = files.find((file) => file.path === '.wapkpatch');
    if (!patchManifest) {
        throw new Error('Patch archive must include a .wapkpatch manifest file.');
    }

    const patterns = parsePatternLines(patchManifest.content.toString('utf8'));
    if (patterns.length === 0) {
        throw new Error('Patch archive .wapkpatch must define at least one patch rule.');
    }

    return patterns;
}

function applyPatchEntriesToFiles(
    targetFiles: readonly WapkFileEntry[],
    patchFiles: readonly WapkFileEntry[],
): Omit<WapkPatchResult, 'archiveLabel'> & { files: WapkFileEntry[] } {
    const fileMap = new Map<string, WapkFileEntry>(targetFiles.map((file) => [file.path, file]));
    const fileOrder = targetFiles.map((file) => file.path);
    const addedPaths: string[] = [];
    const updatedPaths: string[] = [];
    const unchangedPaths: string[] = [];

    for (const patchFile of [...patchFiles].sort((left, right) => left.path.localeCompare(right.path))) {
        const existing = fileMap.get(patchFile.path);
        const nextEntry: WapkFileEntry = {
            path: patchFile.path,
            content: Buffer.from(patchFile.content),
            mode: patchFile.mode,
        };

        if (!existing) {
            addedPaths.push(patchFile.path);
            fileOrder.push(patchFile.path);
        } else if (existing.mode === patchFile.mode && existing.content.equals(patchFile.content)) {
            unchangedPaths.push(patchFile.path);
        } else {
            updatedPaths.push(patchFile.path);
        }

        fileMap.set(patchFile.path, nextEntry);
    }

    return {
        files: fileOrder.map((filePath) => {
            const file = fileMap.get(filePath);
            if (!file) {
                throw new Error(`Internal WAPK patch error: missing file entry for ${filePath}`);
            }

            return file;
        }),
        patchedPaths: [...updatedPaths, ...addedPaths],
        addedPaths,
        updatedPaths,
        unchangedPaths,
    };
}

function collectFiles(directory: string, baseDirectory: string, ignorePatterns: readonly string[]): WapkFileEntry[] {
    const files: WapkFileEntry[] = [];
    const entries = readdirSync(directory, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = join(directory, entry.name);
        const relativePath = relative(baseDirectory, fullPath).split('\\').join('/');
        if (shouldIgnore(relativePath, ignorePatterns, entry.isDirectory())) {
            continue;
        }

        if (entry.isSymbolicLink()) {
            try {
                const stats = statSync(fullPath);
                if (stats.isDirectory() && relativePath.split('/').includes('node_modules')) {
                    files.push(...collectLinkedPackageFiles(fullPath, relativePath));
                } else if (stats.isFile()) {
                    files.push({
                        path: relativePath,
                        content: readFileSync(fullPath),
                        mode: stats.mode,
                    });
                }
            } catch {
                continue;
            }

            continue;
        }

        if (entry.isDirectory()) {
            files.push(...collectFiles(fullPath, baseDirectory, ignorePatterns));
            continue;
        }

        if (!entry.isFile()) {
            continue;
        }

        const stat = statSync(fullPath);
        files.push({
            path: relativePath,
            content: readFileSync(fullPath),
            mode: stat.mode,
        });
    }

    return files;
}

function collectNestedEntryPackageFiles(sourceDirectory: string, entry: string): WapkFileEntry[] {
    const entryPath = resolve(sourceDirectory, entry);
    const entryPackageDirectory = findNearestPackageDirectory(dirname(entryPath), sourceDirectory);

    if (!entryPackageDirectory || resolve(entryPackageDirectory) === resolve(sourceDirectory)) {
        return [];
    }

    const relativePackageDirectory = relative(sourceDirectory, entryPackageDirectory).split('\\').join('/');
    if (!relativePackageDirectory || relativePackageDirectory.startsWith('..') || isAbsolute(relativePackageDirectory)) {
        return [];
    }

    const packageJson = readJsonFile(join(entryPackageDirectory, 'package.json'));
    if (!packageJson) {
        return [];
    }

    const collected = new Map<string, WapkFileEntry>();
    const seenPackages = new Set<string>();

    for (const dependencyName of collectInstalledPackageNames(packageJson)) {
        const dependencyDirectory = resolveInstalledPackageDirectory(entryPackageDirectory, dependencyName)
            ?? resolveInstalledPackageDirectory(sourceDirectory, dependencyName);
        if (!dependencyDirectory) {
            continue;
        }

        const dependencyEntries = collectLinkedPackageFiles(
            dependencyDirectory,
            `${relativePackageDirectory}/node_modules/${dependencyName}`,
            seenPackages,
        );

        for (const entryFile of dependencyEntries) {
            collected.set(entryFile.path, entryFile);
        }
    }

    return [...collected.values()];
}

function encodeWapkPayload(header: WapkHeader, files: readonly WapkFileEntry[]): Buffer {
    const headerBuffer = Buffer.from(JSON.stringify(header, null, 2), 'utf8');
    let totalSize = 4 + headerBuffer.length + 4;

    for (const file of files) {
        const pathBuffer = Buffer.from(file.path, 'utf8');
        totalSize += 2 + pathBuffer.length + 4 + 4 + file.content.length;
    }

    const buffer = Buffer.allocUnsafe(totalSize);
    let offset = 0;

    buffer.writeUInt32LE(headerBuffer.length, offset);
    offset += 4;
    headerBuffer.copy(buffer, offset);
    offset += headerBuffer.length;

    buffer.writeUInt32LE(files.length, offset);
    offset += 4;

    for (const file of files) {
        const pathBuffer = Buffer.from(file.path, 'utf8');
        buffer.writeUInt16LE(pathBuffer.length, offset);
        offset += 2;
        pathBuffer.copy(buffer, offset);
        offset += pathBuffer.length;
        buffer.writeUInt32LE(file.mode ?? 0o644, offset);
        offset += 4;
        buffer.writeUInt32LE(file.content.length, offset);
        offset += 4;
        file.content.copy(buffer, offset);
        offset += file.content.length;
    }

    return buffer;
}

function encodeWapk(header: WapkHeader, files: readonly WapkFileEntry[], lock?: ResolvedWapkCredentials): Buffer {
    const payload = encodeWapkPayload(header, files);

    if (!lock) {
        const buffer = Buffer.allocUnsafe(WAPK_MAGIC.length + 2 + payload.length);
        let offset = 0;

        WAPK_MAGIC.copy(buffer, offset);
        offset += WAPK_MAGIC.length;
        buffer.writeUInt16LE(WAPK_UNLOCKED_VERSION, offset);
        offset += 2;
        payload.copy(buffer, offset);

        return buffer;
    }

    const encrypted = encryptWapkPayload(payload, lock);
    const metadataBuffer = Buffer.from(JSON.stringify(encrypted.metadata), 'utf8');
    const buffer = Buffer.allocUnsafe(
        WAPK_MAGIC.length + 2 + 4 + metadataBuffer.length + 4 + encrypted.payload.length,
    );
    let offset = 0;

    WAPK_MAGIC.copy(buffer, offset);
    offset += WAPK_MAGIC.length;
    buffer.writeUInt16LE(WAPK_LOCKED_VERSION, offset);
    offset += 2;
    buffer.writeUInt32LE(metadataBuffer.length, offset);
    offset += 4;
    metadataBuffer.copy(buffer, offset);
    offset += metadataBuffer.length;
    buffer.writeUInt32LE(encrypted.payload.length, offset);
    offset += 4;
    encrypted.payload.copy(buffer, offset);

    return buffer;
}

function decodeWapkPayload(buffer: Buffer): Omit<DecodedWapk, 'version' | 'lock'> {
    let offset = 0;

    ensureBufferRange(buffer, offset, 4, 'header length');
    const headerLength = buffer.readUInt32LE(offset);
    offset += 4;

    ensureBufferRange(buffer, offset, headerLength, 'header');
    const rawHeader = JSON.parse(buffer.slice(offset, offset + headerLength).toString('utf8'));
    offset += headerLength;
    if (!isRecord(rawHeader)) {
        throw new Error('Invalid WAPK file: header must be an object.');
    }

    ensureBufferRange(buffer, offset, 4, 'file count');
    const fileCount = buffer.readUInt32LE(offset);
    offset += 4;

    const header: WapkHeader = {
        name: typeof rawHeader.name === 'string' ? rawHeader.name : 'app',
        version: typeof rawHeader.version === 'string' ? rawHeader.version : '1.0.0',
        runtime: normalizeRuntime(rawHeader.runtime ?? rawHeader.engine) ?? 'node',
        entry: typeof rawHeader.entry === 'string' ? rawHeader.entry : 'index.js',
        scripts: normalizeStringMap(rawHeader.scripts) ?? {},
        appId: normalizeNonEmptyString(rawHeader.appId),
        publisherId: normalizeNonEmptyString(rawHeader.publisherId),
        port: normalizePort(rawHeader.port),
        env: normalizeStringMap(rawHeader.env),
        desktop: normalizeDesktopConfig(rawHeader.desktop),
        createdAt: typeof rawHeader.createdAt === 'string' ? rawHeader.createdAt : new Date(0).toISOString(),
    };

    const files: WapkFileEntry[] = [];
    for (let index = 0; index < fileCount; index++) {
        ensureBufferRange(buffer, offset, 2, `file ${index + 1} path length`);
        const pathLength = buffer.readUInt16LE(offset);
        offset += 2;

        ensureBufferRange(buffer, offset, pathLength, `file ${index + 1} path`);
        const pathValue = buffer.slice(offset, offset + pathLength).toString('utf8');
        offset += pathLength;

        ensureBufferRange(buffer, offset, 4, `file ${index + 1} mode`);
        const mode = buffer.readUInt32LE(offset);
        offset += 4;

        ensureBufferRange(buffer, offset, 4, `file ${index + 1} size`);
        const contentLength = buffer.readUInt32LE(offset);
        offset += 4;

        ensureBufferRange(buffer, offset, contentLength, `file ${index + 1} content`);
        const content = Buffer.allocUnsafe(contentLength);
        buffer.copy(content, 0, offset, offset + contentLength);
        offset += contentLength;

        files.push({ path: pathValue, content, mode });
    }

    return { header, files };
}

export function decodeWapk(buffer: Buffer, options: WapkCredentialsOptions = {}): DecodedWapk {
    const envelope = parseWapkEnvelope(buffer);

    if (envelope.version === WAPK_UNLOCKED_VERSION) {
        return {
            version: envelope.version,
            ...decodeWapkPayload(envelope.payload),
        };
    }

    const credentials = resolveArchiveCredentials(options);
    if (!credentials) {
        throw new Error('WAPK archive is password-protected. Provide --password to unlock it.');
    }

    return {
        version: envelope.version,
        ...decodeWapkPayload(decryptWapkPayload(envelope.payload, envelope.lock, credentials)),
        lock: { password: true },
    };
}

export function filesEqual(left: readonly WapkFileEntry[], right: readonly WapkFileEntry[]): boolean {
    if (left.length !== right.length) {
        return false;
    }

    for (let index = 0; index < left.length; index++) {
        const leftEntry = left[index];
        const rightEntry = right[index];
        if (leftEntry.path !== rightEntry.path || leftEntry.mode !== rightEntry.mode) {
            return false;
        }

        if (!leftEntry.content.equals(rightEntry.content)) {
            return false;
        }
    }

    return true;
}

export function extractFiles(files: readonly WapkFileEntry[], destination: string): void {
    for (const file of files) {
        const filePath = join(destination, file.path);
        mkdirSync(dirname(filePath), { recursive: true });
        writeFileSync(filePath, file.content);
        if (process.platform !== 'win32') {
            try {
                chmodSync(filePath, file.mode);
            } catch {
                continue;
            }
        }
    }
}

export function collectRuntimeSyncFiles(
    directory: string,
    options: { includeNodeModules?: boolean } = {},
): WapkFileEntry[] {
    return filterRuntimeSyncFiles(collectFiles(directory, directory, []), options);
}

export function filterRuntimeSyncFiles(
    files: readonly WapkFileEntry[],
    options: { includeNodeModules?: boolean } = {},
): WapkFileEntry[] {
    return [...files]
        .filter((file) => {
            const firstPart = file.path.split('/')[0] ?? '';
            if (RUNTIME_SYNC_IGNORE.has(firstPart)) {
                return false;
            }

            if (!options.includeNodeModules && firstPart === 'node_modules') {
                return false;
            }

            return true;
        })
        .sort((left, right) => left.path.localeCompare(right.path));
}

export async function writeWapkArchiveFromMemory(
    archiveHandle: WapkArchiveHandle,
    header: WapkHeader,
    files: readonly WapkFileEntry[],
    lock?: ResolvedWapkCredentials,
): Promise<{ header: WapkHeader; signature?: string; label: string }> {
    const updatedHeader: WapkHeader = {
        ...header,
        createdAt: new Date().toISOString(),
    };
    const snapshot = await archiveHandle.writeBuffer(encodeWapk(updatedHeader, files, lock));
    return {
        header: updatedHeader,
        signature: snapshot.signature,
        label: snapshot.label ?? archiveHandle.label,
    };
}

function removeEmptyParentDirectories(directory: string, rootDir: string): void {
    let currentDir = directory;

    while (true) {
        const relativeDir = relative(rootDir, currentDir);
        if (!relativeDir || relativeDir.startsWith('..') || isAbsolute(relativeDir)) {
            return;
        }

        try {
            if (readdirSync(currentDir).length > 0) {
                return;
            }

            rmSync(currentDir, { recursive: false, force: true });
        } catch {
            return;
        }

        currentDir = dirname(currentDir);
    }
}

export function applyArchiveFilesToWorkDir(
    directory: string,
    files: readonly WapkFileEntry[],
    options: { includeNodeModules?: boolean } = {},
): void {
    const existingFiles = collectRuntimeSyncFiles(directory, options);
    const nextPaths = new Set(files.map((file) => file.path));

    for (const file of existingFiles) {
        if (nextPaths.has(file.path)) {
            continue;
        }

        const filePath = join(directory, ...file.path.split('/'));
        rmSync(filePath, { force: true });
        removeEmptyParentDirectories(dirname(filePath), directory);
    }

    extractFiles(files, directory);
}

export async function readArchiveRuntimeState(
    archiveHandle: WapkArchiveHandle,
    lock?: ResolvedWapkCredentials,
    options: { includeNodeModules?: boolean } = {},
): Promise<{ header: WapkHeader; files: WapkFileEntry[]; signature?: string; label: string }> {
    const snapshot = await archiveHandle.readSnapshot();
    const decoded = decodeWapk(snapshot.buffer, lock ? { password: lock.password } : {});

    return {
        header: decoded.header,
        files: filterRuntimeSyncFiles(decoded.files, options),
        signature: snapshot.signature,
        label: snapshot.label ?? archiveHandle.label,
    };
}

export function readWapkArchive(wapkPath: string, options: WapkCredentialsOptions = {}): DecodedWapk {
    const archivePath = resolve(wapkPath);
    if (!existsSync(archivePath)) {
        throw new Error(`WAPK file not found: ${archivePath}`);
    }

    return decodeWapk(readFileSync(archivePath), options);
}

export async function packWapkDirectory(
    directory: string,
    options: WapkCredentialsOptions & { includeDeps?: boolean; outputPath?: string } = {},
): Promise<string> {
    const sourceDirectory = resolve(directory);
    if (!existsSync(sourceDirectory) || !statSync(sourceDirectory).isDirectory()) {
        throw new Error(`WAPK source directory not found: ${sourceDirectory}`);
    }

    const config = await readWapkProjectConfig(sourceDirectory);
    const lock = resolvePackLockCredentials(config.lock, options);
    const outputPath = resolve(options.outputPath ?? join(process.cwd(), `${sanitizePackageName(config.name)}.wapk`));
    const relativeOutputPath = relative(sourceDirectory, outputPath).split('\\').join('/');
    const outputPathIsInsideSource = relativeOutputPath.length > 0
        && !relativeOutputPath.startsWith('..')
        && !isAbsolute(relativeOutputPath);
    const userIgnore = readIgnorePatterns(sourceDirectory);
    const ignorePatterns = [...DEFAULT_IGNORE, ...userIgnore];
    const collectedFiles = collectFiles(sourceDirectory, sourceDirectory, ignorePatterns);
    const nestedEntryPackageFiles = collectNestedEntryPackageFiles(sourceDirectory, config.entry);
    const fileMap = new Map<string, WapkFileEntry>();
    for (const file of [...collectedFiles, ...nestedEntryPackageFiles]) {
        if (outputPathIsInsideSource && file.path === relativeOutputPath) {
            continue;
        }
        fileMap.set(file.path, file);
    }
    const files = [...fileMap.values()];
    const header: WapkHeader = {
        name: config.name,
        version: config.version,
        runtime: config.runtime,
        entry: config.entry,
        scripts: config.scripts,
        appId: config.appId,
        publisherId: config.publisherId,
        port: config.port,
        env: config.env,
        desktop: config.desktop,
        createdAt: new Date().toISOString(),
    };

    console.log(`Packing: ${config.name}@${config.version}`);
    console.log(`Runtime: ${config.runtime}`);
    console.log(`Entry:   ${config.entry}`);
    if (lock) {
        console.log('Lock:    enabled');
    }
    if (files.some((file) => file.path.split('/').includes('node_modules'))) {
        console.log('Deps:    included');
    }
    if (options.includeDeps) {
        console.log('Note:    --include-deps is no longer required; node_modules are packed by default');
    }
    console.log(`Files:   ${files.length}`);

    writeFileSync(outputPath, encodeWapk(header, files, lock));
    console.log(`Output:  ${outputPath}`);
    return outputPath;
}

export function extractWapkArchive(
    wapkPath: string,
    outputDir = '.',
    options: WapkCredentialsOptions = {},
): string {
    const archive = readWapkArchive(wapkPath, options);
    const destinationRoot = resolve(outputDir);
    const extractDirectory = join(destinationRoot, sanitizePackageName(archive.header.name));

    mkdirSync(extractDirectory, { recursive: true });
    extractFiles(archive.files, extractDirectory);
    console.log(`Extracted ${archive.files.length} files to: ${extractDirectory}`);
    return extractDirectory;
}

export async function patchWapkArchive(
    wapkPath: string,
    options: WapkCredentialsOptions & {
        from: string;
        fromPassword?: string;
    },
): Promise<WapkPatchResult> {
    const targetHandle = resolveArchiveHandle(wapkPath);
    const targetSnapshot = await targetHandle.readSnapshot();
    const targetEnvelope = parseWapkEnvelope(targetSnapshot.buffer);
    const targetArchive = decodeWapk(targetSnapshot.buffer, options);
    const targetLock = targetEnvelope.version === WAPK_LOCKED_VERSION
        ? resolveArchiveCredentials(options)
        : undefined;
    const patchArchive = readWapkArchive(options.from, {
        password: options.fromPassword ?? options.password,
    });
    const patchPatterns = resolvePatchManifestPatterns(patchArchive.files);
    const selectedPatchFiles = patchArchive.files
        .filter((file) => file.path !== '.wapkpatch')
        .filter((file) => shouldPatchArchivePath(file.path, patchPatterns));
    const patchResult = applyPatchEntriesToFiles(targetArchive.files, selectedPatchFiles);

    console.log(`[wapk] Target: ${targetSnapshot.label ?? targetHandle.label}`);
    console.log(`[wapk] Patch:  ${options.from}`);
    console.log(`[wapk] Rules:  ${patchPatterns.length}`);

    if (selectedPatchFiles.length === 0) {
        console.log('[wapk] No files matched .wapkpatch. Archive was not modified.');
        return {
            archiveLabel: targetSnapshot.label ?? targetHandle.label,
            patchedPaths: [],
            addedPaths: [],
            updatedPaths: [],
            unchangedPaths: [],
        };
    }

    if (patchResult.patchedPaths.length === 0) {
        console.log('[wapk] Matching patch files were already up to date. Archive was not modified.');
        return {
            archiveLabel: targetSnapshot.label ?? targetHandle.label,
            patchedPaths: [],
            addedPaths: [],
            updatedPaths: [],
            unchangedPaths: patchResult.unchangedPaths,
        };
    }

    const writeResult = await writeWapkArchiveFromMemory(
        targetHandle,
        targetArchive.header,
        patchResult.files,
        targetLock,
    );

    console.log(`[wapk] Applied ${patchResult.patchedPaths.length} patch file${patchResult.patchedPaths.length === 1 ? '' : 's'}.`);

    return {
        archiveLabel: writeResult.label,
        patchedPaths: patchResult.patchedPaths,
        addedPaths: patchResult.addedPaths,
        updatedPaths: patchResult.updatedPaths,
        unchangedPaths: patchResult.unchangedPaths,
    };
}