export const DESKTOP_RENDER_TRACKED_KEY = '__ELIT_DESKTOP_RENDER_TRACKED__';
export const DESKTOP_WINDOW_CREATED_KEY = '__ELIT_DESKTOP_WINDOW_CREATED__';
export const DESKTOP_MESSAGE_HANDLER_KEY = '__ELIT_DESKTOP_MESSAGE_HANDLER__';