export const RUNTIME_TARGET_KEY = '__ELIT_RUNTIME_TARGET__';
export const CAPTURED_RENDER_KEY = '__ELIT_CAPTURED_RENDER__';
export const DESKTOP_RENDER_OPTIONS_KEY = '__ELIT_DESKTOP_RENDER_OPTIONS__';
export const RUNTIME_TARGET_ENV = 'ELIT_RUNTIME_TARGET';