name: Setup Package

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      package:
        required: true
        type: string
      pkgVersion:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string
      build_package:
        required: true
        type: boolean

permissions:
  contents: read
  packages: write  # สำหรับ publish package
  id-token: write

jobs:

  publish:
    if: inputs.build_package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.nodeVersion }}"
          cache: npm
          registry-url: 'https://registry.npmjs.org'  # เขียน NODE_AUTH_TOKEN ลง .npmrc ให้ publish ได้

      - name: Install dependencies
        working-directory: ./packages/${{ inputs.package }}
        run: npm ci

      - name: Build ${{ inputs.package }}@${{ inputs.pkgVersion }}
        working-directory: ./packages/${{ inputs.package }}
        run: npm run build

      - name: Publish ${{ inputs.package }}@${{ inputs.pkgVersion }}
        run: |
          OWNER=${GITHUB_REPOSITORY%/*}
          PACKAGE_NAME=${{ inputs.package }}
          VERSION=${{ inputs.pkgVersion }}
          TAG=${{ inputs.environment }}

          echo "📦 Publishing $PACKAGE_NAME@$VERSION with tag '$TAG'"

          npm version $VERSION --prefix ./packages/$PACKAGE_NAME --no-git-tag-version
          npm publish ./packages/$PACKAGE_NAME \
            --tag $TAG \
            --access public \
            --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}